# Generated by Django 4.2.9 on 2024-01-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_topic_remove_comment_post_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicComments',
        ),
    ]
