# Generated by Django 4.2.9 on 2024-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_topiccomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(default='Ogólne', max_length=127),
        ),
    ]
