# Generated by Django 4.2.9 on 2024-01-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
    ]
